#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += jd9161ba_dsi_vdo_fwvga_zhongguangdian_HSD52.o



ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc


